### ISSUE TITLE
Remove qiskit_metal imports in toolbox_python.utility_functions

### ISSUE THREAD

**Issue by grace-harper-ibm** [Qiskit/qiskit-metal#523]
### Information

- **Qiskit Metal version**:
- **Python version**:
- **Operating system**:

### What is the current behavior?

Importing python_toolbox methods into qiskit_metal can result in circular dependencies since 
`toolbox_python.utility_functions`
contains
`from qiskit_metal.draw import Vector`

If we move those Vector-specific functions (bad_fillet_idxs, get_range_of_vertex_to_not_fillet) into a class for Vectors outside of toolbox_python, we can then use toolbox_python.utility_functions  for all functions that are python specific but have no qiskit_metal parts. 

### Steps to reproduce the problem
Example: I was unable to add a `get_class_from_abs_file_path` to toolbox_python.utility_files to be used in both `parameter_entry_window.py` and 'delegate_qlibrary.py` because of the of the resulting circular import chain: 

```
Traceback (most recent call last):
  File "/home/runner/work/qiskit-metal/qiskit-metal/.tox/docs/lib/python3.7/site-packages/sphinx/config.py", line 327, in eval_config_file
    execfile_(filename, namespace)
  File "/home/runner/work/qiskit-metal/qiskit-metal/.tox/docs/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 88, in execfile_
    exec(code, _globals)
  File "/home/runner/work/qiskit-metal/qiskit-metal/docs/conf.py", line 32, in <module>
    import qiskit_metal
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/__init__.py", line 110, in <module>
    from .toolbox_metal.parsing import is_true
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/toolbox_metal/__init__.py", line 59, in <module>
    from . import import_export
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/toolbox_metal/import_export.py", line 22, in <module>
    from ..toolbox_python.utility_functions import log_error_easy
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/toolbox_python/utility_functions.py", line 29, in <module>
    from qiskit_metal.draw import Vector
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/draw/__init__.py", line 26, in <module>
    from . import mpl
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/draw/mpl.py", line 19, in <module>
    from ..renderers.renderer_mpl.mpl_toolbox import *
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/renderers/__init__.py", line 80, in <module>
    from .renderer_mpl.mpl_canvas import PlotCanvas
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/renderers/renderer_mpl/mpl_canvas.py", line 48, in <module>
    from .extensions.animated_text import AnimatedText
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/renderers/renderer_mpl/extensions/animated_text.py", line 19, in <module>
    from ...._gui.utility._handle_qt_messages import slot_catch_error
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/_gui/__init__.py", line 47, in <module>
    from qiskit_metal._gui.main_window import QMainWindowExtension
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/_gui/main_window.py", line 26, in <module>
    from qiskit_metal._gui.widgets.qlibrary_display.delegate_qlibrary import LibraryDelegate
  File "/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/_gui/widgets/qlibrary_display/delegate_qlibrary.py", line 23, in <module>
    from qiskit_metal.toolbox_python.utility_functions import get_class_from_abs_file_path
ImportError: cannot import name 'get_class_from_abs_file_path' from 'qiskit_metal.toolbox_python.utility_functions' (/home/runner/work/qiskit-metal/qiskit-metal/qiskit_metal/toolbox_python/utility_functions.py)

```

### What is the expected behavior?
I'm suggesting that `toolbox_python.utility_functions` should be for functions that don't rely on qiskit_metal specific imports, meaning and `toolbox_python.utility_functions` functions can be used throughout qiskit_metal without fear of circular imports 

### Suggested solutions
If we move those Vector-specific functions (bad_fillet_idxs, get_range_of_vertex_to_not_fillet) into a class for Vectors outside of toolbox_python, we can then use toolbox_python.utility_functions  for all functions that are python specific but have no qiskit_metal parts.

**Comment by priti-ashvin-shah-ibm** [comment]
We don't have any circular import issues.  They have been addressed.
